WebPlatform/Models/Administration/UserRole/UserRole.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;
using WebPlatform.CORE;

namespace WebPlatform.Models.Administration
{
    public class UserRole : BaseEntity
    {
        public int RoleId { get; set; }
        public string UserId { get; set; }
    }

    public class UserRoleConfiguration : EntityTypeConfiguration<UserRole>
    {
        public UserRoleConfiguration()
        {
            ToTable("AdmUserRole");
            HasKey(e => new { e.RoleId, e.UserId });           
            Ignore(e => e.Id);

        }
    }
}

WebPlatform/ViewModels/Administration/UserRole/UserRoleModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebPlatform.CORE;

namespace WebPlatform.ViewModels.Administration
{
    public class UserRoleModel : BaseModel
    {
        public int RoleId { get; set; }
        public string UserGuid { get; set; }
        public bool IsAssigned { get; set; }
        public string RoleName { get; set; }
        public string RoleGuid { get; set; }
        public string UserName { get; set; }
    }
}

WebPlatform/ViewModels/Administration/UserRole/UserRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatform.CORE;

namespace WebPlatform.ViewModels.Administration
{
    public class UserRoleViewModel : BaseViewModel<UserRoleModel>
    {
        public int RoleId { get; set; }
        public string UserGuid { get; set; }
        public bool IsAssigned { get; set; }
        public string RoleName { get; set; }
        public string RoleGuid { get; set; }
        public string UserName { get; set; }

    }
}

WebPlatform/Controllers/UserRoleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPlatform.Models;
using WebPlatform.Models.Administration;
using WebPlatform.Services.Administration;
using WebPlatform.ViewModels.Administration;
using WebPlatform.CORE.Helpers;
using WebPlatform.Services;
using WebPlatform.Services.Administration.User;

namespace WebPlatform.Controllers
{
    public class UserRoleController : BaseController
    {

        private UserRoleService _service;
        private RoleService _roleService;
        private UserService _userService;

        public UserRoleController(UserRoleService service, RoleService roleService, UserService userService)
        {
            _service = service;
            _roleService = roleService;
            _userService = userService;
        }

        public async Task<ActionResult> AssignRole(string userGuid)
        {
            if (string.IsNullOrEmpty(userGuid)) return HttpNotFound();
            var vm = new UserRoleViewModel();
            var roles = await _roleService.GetAllAsync();
            var user = await _userService.GetByIdAsync(userGuid);
            var junctionList = await _service.GetAllByUserIdAsync(user.Id);

            IList<UserRoleModel> list = _service.GenerateRolesAssignment(roles, junctionList, user.Id);
           
            vm.Elements = list;
            vm.UserGuid = user.RowGuid;
            vm.UserName = user.UserName;
            return PartialView(vm);
        }

       

        [HttpPost]
        public async Task<ActionResult> AssignChange(Guid roleGuid, Guid userGuid)
        {
            var role = await _roleService.GetByGuidAsync(roleGuid.ToString());
            var user = await _userService.GetByIdAsync(userGuid.ToString());
            if (null == role || null == user) return HttpNotFound();
            await _service.AddOrDeleteAsync(new UserRoleModel { RoleId = role.Id, UserGuid = user.Id });
            return RedirectToAction("AssignRole", new { userGuid = user.RowGuid.ToString() } );
        }

        

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _service = null;
            }
            base.Dispose(disposing);
        }
    }
}

WebPlatform/Views/UserRole/AssignRole.cshtml
@model WebPlatform.ViewModels.Administration.UserRoleViewModel

@{
    Layout = null;
}

@using (Html.UI().Begin(new Container(ContainerType.Standard)))
{

    using (Html.UI().Begin(new RowBox()))
    {
        using (Html.UI().Begin(new ColBox().AddClass("text-center")))
        {
            using (Html.UI().Begin(new HBox(HeaderSize.H3)))
            {
                <span>
                    @Model.UserName
                </span>
            }
        }

    }

    using (Html.UI().Begin(new RowBox()))
    {
        if (!Model.Elements.Any())
        {
            using (Html.UI().Begin(new HBox(HeaderSize.H3)))
            {
                <span>
                    Brak dostępnych ról użytkowników
                </span>
            }
        }
        else
        {
            foreach (var item in Model.Elements)
            {
                using (Html.UI().Begin(new ColBox(12).AddClass("role-box text-center")))
                {
                    using (Html.UI().Begin(new RowBox()))
                    {
                        using (Html.UI().Begin(new ColBox(8)))
                        {
                            using (Html.UI().Begin(new ParagraphBox()))
                            {
                                @(item.RoleName)
                            }
                        }
                        using (Html.UI().Begin(new ColBox(4).AddClass("assign-unassign")))
                        {
                            if (item.IsAssigned)
                            {
                                using (Html.UI().Begin(new Box().AddClass("greenpoint assign-change")
                                    .AddData("user-guid", Model.UserGuid)
                                    .AddData("roleguid", item.RoleGuid))) { }
                            }
                            else
                            {
                                using (Html.UI().Begin(new Box().AddClass("greypoint assign-change")
                                    .AddData("user-guid", Model.UserGuid)
                                    .AddData("roleguid", item.RoleGuid))) { }

                            }

                        }
                    }
                }

            }
        }


    }
}

<script>

    $(document).ready(function(){

        (function () {

            $(".assign-change").click(function () {
                var roleguid = $(this).attr("data-roleguid");
                var userguid = $(this).attr("data-user-guid");
                //console.log(roleguid);
                //console.log(userguid);

                var values = {
                    'roleGuid': roleguid,
                    'userGuid': userguid
                };
                $.ajax({
                    url: "@(Url.Action("AssignChange", "UserRole", null))",
                    type: "POST",
                    data: values,
                    success: function (data) {
                        $("#wppopup .modal-body").html(data);
                    },
                    error: function () {
                        console.log("error");
                    }
                });


            });


        })();

    });

</script>