WebPlatform/Models/Administration/RoleResource/RoleResource.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.ModelConfiguration;
using System.Linq;
using System.Web;
using WebPlatform.CORE;

namespace WebPlatform.Models.Administration
{
    public class RoleResource : BaseEntity
    {
        public int RoleId { get; set; }
        public int ResourceId { get; set; }
    }

    public class RoleResourceConfiguration : EntityTypeConfiguration<RoleResource>
    {
        public RoleResourceConfiguration()
        {
            ToTable("AdmRoleResource");
            HasKey(e => new { e.RoleId, e.ResourceId });
            //HasRequired(e => e.Roles).WithMany().HasForeignKey(e => e.RoleId);
            //HasRequired(e => e.Resources).WithMany().HasForeignKey(e => e.ResourceId);
            Ignore(e => e.Id);

        }
    }
}

WebPlatform/ViewModels/Administration/RoleResource/RoleResourceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebPlatform.CORE;

namespace WebPlatform.ViewModels.Administration
{
    public class RoleResourceModel : BaseModel
    {
        public int RoleId { get; set; }
        public int ResourceId { get; set; }
        public bool IsAssigned { get; set; }
        public string RoleName { get; set; }
        public string RoleGuid { get; set; }
        
    }
}

WebPlatform/ViewModels/Administration/RoleResource/RoleResourceViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPlatform.CORE;

namespace WebPlatform.ViewModels.Administration
{
    public class RoleResourceViewModel : BaseViewModel<RoleResourceModel>
    {
        public string ResorceName { get; set; }

        public bool IsAssigned { get; set; }
        public int ResourceId { get; set; }
        public string ResourceGuid { get; set; }
        public string RoleName { get; set; }

    }
}

WebPlatform/Controllers/RoleResourceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPlatform.Models;
using WebPlatform.Models.Administration;
using WebPlatform.Services.Administration;
using WebPlatform.ViewModels.Administration;
using WebPlatform.CORE.Helpers;
using WebPlatform.Services;

namespace WebPlatform.Controllers
{
    public class RoleResourceController : BaseController
    {

        private RoleResourceService _service;
        private ResourceService _resourceService;
        private RoleService _roleService;

        public RoleResourceController(RoleResourceService service, RoleService roleService, ResourceService resourceService)
        {
            _service = service;
            _resourceService = resourceService;
            _roleService = roleService;
        }

        public async Task<ActionResult> AssignRole(string resourceGuid)
        {
            if (string.IsNullOrEmpty(resourceGuid)) return HttpNotFound();
            var vm = new RoleResourceViewModel();
            var roles = await _roleService.GetAllAsync();
            var resource = await _resourceService.GetByGuidAsync(resourceGuid);
            var junctionList = await _service.GetAllByResourceId(resource.Id);

            IList<RoleResourceModel> list = _service.GenerateRolesAssignment(roles, junctionList, resource.Id);
           
            vm.Elements = list;
            vm.ResourceId = resource.Id;
            vm.ResourceGuid = resource.RowGuid;
            vm.ResorceName = resource.Description;
            return PartialView(vm);
        }

        [HttpPost]
        public async Task<ActionResult> AssignChange(Guid roleGuid, Guid resourceGuid)
        {
            var role = await _roleService.GetByGuidAsync(roleGuid.ToString());
            var resource = await _resourceService.GetByGuidAsync(resourceGuid.ToString());
            if (null == role || null == resource) return HttpNotFound();
            await _service.AddOrDeleteAsync(new RoleResourceModel { RoleId = role.Id, ResourceId = resource.Id });
            return RedirectToAction("AssignRole", new { resourceGuid = resource.RowGuid.ToString() } );
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _service = null;
            }
            base.Dispose(disposing);
        }
    }
}

WebPlatform/Views/RoleResource/AssignRole.cshtml
@model WebPlatform.ViewModels.Administration.RoleResourceViewModel

@{
    Layout = null;
}

@using (Html.UI().Begin(new Container(ContainerType.Standard)))
{

    using (Html.UI().Begin(new RowBox()))
    {
        using (Html.UI().Begin(new ColBox().AddClass("text-center")))
        {
            using (Html.UI().Begin(new HBox(HeaderSize.H3)))
            {
                <span>
                    @Model.ResorceName
                </span>
            }
        }

    }

    using (Html.UI().Begin(new RowBox()))
    {
        if (!Model.Elements.Any())
        {
            using (Html.UI().Begin(new HBox(HeaderSize.H3)))
            {
                <span>
                    Brak dostępnych ról użytkowników
                </span>
            }
        }
        else
        {
            foreach (var item in Model.Elements)
            {
                using (Html.UI().Begin(new ColBox(12).AddClass("role-box text-center")))
                {
                    using (Html.UI().Begin(new RowBox()))
                    {
                        using (Html.UI().Begin(new ColBox(8)))
                        {
                            using (Html.UI().Begin(new ParagraphBox()))
                            {
                                @(item.RoleName)
                            }
                        }
                        using (Html.UI().Begin(new ColBox(4).AddClass("assign-unassign")))
                        {
                            if (item.IsAssigned)
                            {
                                using (Html.UI().Begin(new Box().AddClass("greenpoint assign-change")
                                    .AddData("resource-guid", Model.ResourceGuid)
                                    .AddData("roleguid", item.RoleGuid))) { }
                            }
                            else
                            {
                                using (Html.UI().Begin(new Box().AddClass("greypoint assign-change")
                                    .AddData("resource-guid", Model.ResourceGuid)
                                    .AddData("roleguid", item.RoleGuid))) { }

                            }

                        }
                    }
                }

            }
        }


    }
}

<script>

    $(document).ready(function(){

        (function () {

            $(".assign-change").click(function () {
                var roleguid = $(this).attr("data-roleguid");
                var resourceguid = $(this).attr("data-resource-guid");
                //console.log(roleguid);
                //console.log(resourceguid);

                var values = {
                    'roleGuid': roleguid,
                    'resourceGuid': resourceguid
                };
                $.ajax({
                    url: "@(Url.Action("AssignChange", "RoleResource", null))",
                    type: "POST",
                    data: values,
                    success: function (data) {
                        $("#wppopup .modal-body").html(data);
                    },
                    error: function () {
                        console.log("error");
                    }
                });


            });


        })();

    });

</script>