WebPlatform/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebPlatform.Models;
using WebPlatform.Services.Administration;
using WebPlatform.ViewModels.Administration.MenuItem;

namespace WebPlatform.Controllers
{
    public class MenuController : BaseController
    {
        private IMenuItemService _service;

        public MenuController(IMenuItemService service)
        {
            _service = service;
        }

        public MenuController()
        {
            _service = new MenuItemService(new ApplicationDbContext());
        }

        [ChildActionOnly]
        public ActionResult ListItems()
        {
            var all =  _service.GetAllForModel();
            var vm = new MenuItemViewModel();
            vm.Elements = all;
            return PartialView("_carouselRibbonPartial", vm);
        }

        public ActionResult ChangeOpen()
        {
            Session["MenuStateOpen"] = !(bool)Session["MenuStateOpen"];
            bool res = (bool)Session["MenuStateOpen"];
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
    }
}

WebPlatform/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Arima+Madurai" rel="stylesheet">
</head>
<body>

    <script>

        // globals

        var accordionState = { open: 0 };

    </script>

    <section class="container-fluid" id="top-navbar">
        <div class="row">
            <div class="col-10 offset-2">
                <div class="row" id="top-navbar-box">
                    <div class="col-2">
                        @Html.ActionLink("Panel", "Index", "Panel")
                        
                    </div>
                    <div class="col-2">
                       
                        
                    </div>
                    <div class="col-2">
                        
                    </div>
                    <div class="col-4">
                        @Html.Partial("_LoginPartial")
                    </div>
                    
                   
                </div>
            </div>
        </div>

    </section>

    <section class="container-fluid" id="ribbon-box">
        @Html.Action("ListItems", "Menu")
    </section>


    <section id="content-box" class="container-fluid">
        @RenderBody()
    </section>

    

    <section id="logged-footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col text-center">
                    Kolumna lewa
                </div>
                <div class="col text-center">
                    Kolumna prawa
                </div>
            </div>
        </div>
    </section>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    @RenderSection("scripts", required: false)

    <script>
        $(document).ready(function () {

            var ribbon = $("#ribbon-box");
            var footer = $("#logged-footer");
            var docHeight = $(document).height();
            var footerHeight = footer.height();
            var ribbonHeight = ribbon.height();
            var footerTop = footer.position().top + footerHeight;

            if (footerTop < docHeight) {
                footer.css('margin-top', 10 + (docHeight - footerTop + ribbonHeight) + 'px');
            }
                
        });
    </script>

</body>
</html>

WebPlatform/Views/Shared/_LayoutUnlogged.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
</head>
<body class="unlogged">
    
    <div class="container-fluid">
        @RenderBody()
    </div>

    <div class="footer">
        <div class="row">
            <div class="col-4">
                Kolumna lewa
            </div>
            <div class="col-4">
                Kolumna środek
            </div>
            <div class="col-4">
                Kolumna prawa
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>

WebPlatform/Views/Shared/_carouselRibbonPartial.cshtml
@using WebPlatform.ViewModels.Administration
@model WebPlatform.ViewModels.Administration.MenuItem.MenuItemViewModel



@helper RenderItems(MenuItemModel parent)
{

    if (parent.Items.Any())
    {
        <li>
            <div class="trigger" data-trigger="@parent.Id">
                <p>
                    <i class="fas fa-caret-down" data-ico="@parent.Id"></i>
                    @parent.Title
                </p>
            </div>
            <ul class="trigger-list element-hidden" data-trigger="@parent.Id">
                @foreach (var item in parent.Items)
                {
                    @RenderItems(item);
                }

            </ul>
        </li>


    }
    else
    {

        <li>
            <div>
                <p>
                    <i class="fas fa-arrow-right"></i>
                    <a title="@parent.Title" href="@parent.RouteUrl">@parent.Title</a>
                </p>
            </div>

        </li>
    }

}

<div class="accordion-fix-dummy"></div>
<div class="accordion">

    <div class="accordion-fix">
        Menu
    </div>
    <div>

        <div id="slick-wrapper">

            <div id="prevSlickArrow">
                <a href="#">
                    <i class="far fa-arrow-alt-circle-left"></i>
                </a>
            </div>
            <div id="nextSlickArrow">
                <a href="#">
                    <i class="far fa-arrow-alt-circle-right"></i>
                </a>
            </div>
            <div class="ribbon-carousel-slick">


                @foreach (var box in Model.Elements)
                {

                    <div class="ribbon-item-box d-flex justify-content-center align-items-stretch p-2">
                        <div class="ribbon-item hvr-glow">
                            <div class="ribbon-item-img text-center" style="background-image: url(@box.ImageUrl)">
                                <div>
                                    <h3>
                                        @box.Title
                                    </h3>
                                </div>
                            </div>
                            <div class="ribbon-item-content hvr-underline-from-center">
                                <ul style="margin:0.2em;">
                                    @foreach (var item in box.Items)
                                    {
                                        @RenderItems(item);
                                    }

                                </ul>
                            </div>
                        </div>

                    </div>

                }


            </div>



        </div>


    </div>
</div>